<a href="https://colab.research.google.com/github/rakesh22230/Data-Mining-Lab/blob/main/222902030_dataming_Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Health_Dataset.csv")
df.head()

PatientID  Age Gender        BMI  BloodPressure Cholesterol SmokingStatus  \
0  PAT000000   69   Male  23.665197     124.214117      Normal    Non-smoker   
1  PAT000001   34   Male  23.923332      95.892140        High    Non-smoker   
2  PAT000002   38  Other  32.198696     140.675210      Normal        Smoker   
3  PAT000003   41   Male  27.108731     120.719478      Normal        Smoker   
4  PAT000004   33   Male  24.879152     119.744859        High    Non-smoker   

   ExerciseFrequency Diabetic  BloodSugarLevel    Region DiseaseRisk  \
0                7.0       No       112.248421     Urban         Low   
1                2.0       No       101.593794     Urban        High   
2                6.0       No       125.220889     Urban         Low   
3                3.0       No       132.322359  Suburban      Medium   
4                3.0      Yes        96.745489     Urban         Low   

  LastCheckupDate  FollowUpNeeded  
0      2023-08-24               1  
1      2023-09-12               0  
2      2023-05-01               0  
3      2022-05-29               0  
4      2022-11-05               1

In [3]:
df.isnull().sum()

PatientID             995
Age                     0
Gender               1998
BMI                  5054
BloodPressure           0
Cholesterol             0
SmokingStatus           0
ExerciseFrequency    9977
Diabetic                0
BloodSugarLevel         0
Region                  0
DiseaseRisk             0
LastCheckupDate         0
FollowUpNeeded          0
dtype: int64

In [4]:
df.fillna(df.mean(numeric_only=True), inplace=True)
df.fillna(df.mode().iloc[0], inplace=True)


In [7]:
df.isnull().sum()

PatientID            0
Age                  0
Gender               0
BMI                  0
BloodPressure        0
Cholesterol          0
SmokingStatus        0
ExerciseFrequency    0
Diabetic             0
BloodSugarLevel      0
Region               0
DiseaseRisk          0
LastCheckupDate      0
FollowUpNeeded       0
dtype: int64

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col])


In [9]:
X = df.drop("DiseaseRisk", axis=1)
y = df["DiseaseRisk"]


In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)


In [14]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = DecisionTreeClassifier(max_depth=5, random_state=42)
model.fit(X_train, y_train)


DecisionTreeClassifier(max_depth=5, random_state=42)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.60095


In [17]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Confusion Matrix:
 [[    0  2031     8]
 [    0 12006    17]
 [    0  5925    13]]


In [18]:
importance = pd.DataFrame({
    "Feature": df.drop("DiseaseRisk", axis=1).columns,
    "Importance": model.feature_importances_
}).sort_values(by="Importance", ascending=False)

print(importance)


              Feature  Importance
0           PatientID    0.369378
9     BloodSugarLevel    0.252341
11    LastCheckupDate    0.120800
5         Cholesterol    0.062294
3                 BMI    0.058546
6       SmokingStatus    0.052217
1                 Age    0.044575
7   ExerciseFrequency    0.039849
2              Gender    0.000000
4       BloodPressure    0.000000
8            Diabetic    0.000000
10             Region    0.000000
12     FollowUpNeeded    0.000000
